FROM node:lts-alpine3.22 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Production stage
FROM node:lts-alpine3.22
WORKDIR /app
COPY --from=build /app .

EXPOSE 3000

CMD ["npm","run","start"]